branches:
  only:
  - master
install:
- ps: Invoke-WebRequest -Uri http://nuget.org/nuget.exe -OutFile $nuget
- cmd: echo a
- ps: $Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))
before_build:
- ps: dnu restore