branches:
  only:
  - YoloGitOTD

environment:
  login:
    secure: QVVZdMDAB+h7xdgg5hUH0A==
  password:
    secure: cP2Y38dqqK4GfySbblU1Fg==

install:
- ps: src/CodeCakeBuilder/Bootstrap.ps1
- dnvm use -p -r clr 1.0.0-rc1-final
- dnu commands install SimpleGitVersion.DNXCommands
- dnu restore
build_script:
- dnx -p CodeCakeBuilder CodeCakeBuilder -nointeraction
test: off