branches:
  only:
  - YoloGitOTD
install:
- ps: Invoke-WebRequest -Uri http://nuget.org/nuget.exe -OutFile $nuget
- cmd: echo a
- ps: $Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))
- ps: dnvm upgrade -r coreclr
- ps: dnvm list
- ps: dnvm setup
- ps: dnvm use default
- ps: dnvm list
before_build:
- ps: dnu restore
- cmd: cd src\ITI.SkyLord.TestAvecEntity.Tests
- cmd: dnx test
build: off